// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StromForbrok.Api.Data;

#nullable disable

namespace StromForbrok.Api.Migrations
{
    [DbContext(typeof(StromForbrokDbContext))]
    [Migration("20260902215140_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StromForbrok.Api.Domain.Consumption", b =>
                {
                    b.Property<string>("MeteringPointId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Kwh")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("MeteringPointId", "Timestamp");

                    b.HasIndex("Timestamp");

                    b.ToTable("Consumption", (string)null);
                });

            modelBuilder.Entity("StromForbrok.Api.Domain.DegreeDays.DegreeDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Value")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("DegreeDay", (string)null);
                });

            modelBuilder.Entity("StromForbrok.Api.Domain.Weather.Temperature", b =>
                {
                    b.Property<string>("StationId")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("StationId", "Timestamp");

                    b.HasIndex("Timestamp");

                    b.ToTable("Temperature", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
